burotimaguta/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from buyers import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('buyers.urls')),
    path('', include('plots.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyers/urls.py
from django.contrib import admin
from django.urls import path
from buyers import views

app_name="buyers"
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('buyers/', views.buyers, name='buyers'),
    path('buyers/new/', views.create_buyer, name='new_buyer'),
    path('buyers/<int:buyer_id>/', views.buyer_detail, name='buyer_detail'),
    path('buyers/<int:buyer_id>/edit/', views.buyer_update, name='buyer_update'),
    path('payments/', views.all_payments, name='payments'),
    path('payments/new/', views.create_payment, name='create_payment'),
    path('payments/<int:payment_id>/edit/', views.edit_payment, name='edit_payment'),
    path('payments/<int:payment_id>/delete/', views.delete_payment, name='delete_payment')
]

plots/urls.py
from django.urls import path
from plots import views

app_name="plots"
urlpatterns = [
    path('plots/', views.plots, name='plots'),
    path('plots/<int:plot_id>/', views.plot_detail, name='plot_detail'),
    path('plotnumbers/', views.all_plotnumbers, name='plotnumbers'),
    #path('plotnumbers/<int:plotnumber_id>/', views.plotnumber_detail, name='plotnumber_detail')   
]

buyers/models.py
from django.db import models

# Create your models here.
from plots.models import Plot, Plot_Number


class BuyerInfo(models.Model):
    GENDER_OPTIONS =(
        ("M","Male"),
        ("F","Female"),
        ("O","Other")
    )

    RESIDENTIAL_OPTIONS = (
        ('R','Resident'),
        ("NR","Non-Resident")
    )

    PAYMENT_CONTRACT = (
        ("Deposit + 3months","Deposit + 3months"),
        ("Deposit + 6months","Deposit + 6months"),
        ("Deposit + 12months","Deposit + 12months"),
        ("Deposit + 24months","Deposit + 24months"),
        ("OT","OT")
    )
    first_name = models.CharField(max_length=255, null=True)
    middle_name = models.CharField(max_length=255, null=True)
    last_name = models.CharField(max_length=255, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_OPTIONS, null=True)
    residential_status = models.CharField(max_length=2, choices=RESIDENTIAL_OPTIONS, null=True)
    current_address = models.CharField(max_length=100, null=True)
    national_id = models.CharField(max_length=10, unique=True, null=True)
    date_of_birth = models.DateField(null=True)
    kra_pin = models.CharField(max_length=11, unique=True, null=True)
    passport_photo = models.ImageField(blank=True, null=True)
    buyer_personal_number = models.CharField(max_length=50, null=True)
    buyers_email = models.EmailField(unique=True, null=True)
    mobile_phone = models.CharField(max_length=15, null=True)
    date_of_registration = models.DateField(null=True)
    project_assigned = models.ForeignKey(Plot, on_delete=models.CASCADE)
    plot_booked = models.OneToOneField(Plot_Number, on_delete=models.CASCADE)
    contract_type = models.CharField(choices=PAYMENT_CONTRACT, max_length=100, null=True)
    deposit_amount = models.IntegerField(null=True)
    balance_amount = models.IntegerField( null=True)
    registeredBy = models.CharField(max_length=15, null=True)

    def __str__(self):
        return self.first_name + " " + self.last_name


class BuyerPayments(models.Model):
    payment_Methods = (
        ("cash","cash"),
        ("Mpesa","Mpesa"),
        ("Check","Check"),
        ("Bank Deposit","Bank Deposit")
    )

    transaction_Status = (
        ("In Process","In Process"),
        ("Received","Received"),
        ("Verified","Verified")
    )
    transactionId = models.CharField(max_length=15, null=True)
    amount = models.IntegerField(null=True)
    paymentFrom = models.ForeignKey(BuyerInfo, on_delete=models.CASCADE)
    paymentMethod = models.CharField(choices=payment_Methods, max_length=100, null=True)
    paidFor = models.CharField(max_length=15, null=True)
    dateReceived = models.DateField(null=True)
    receivedBy = models.CharField(max_length=15, null=True)
    paymentstatus = models.CharField(choices=transaction_Status,max_length=100, null=True)

    def __str__(self):
        return self.transactionId
    

buyers/forms.py
from crispy_forms.helper import FormHelper
from django import forms
from django.forms import ModelForm
from buyers.models import BuyerInfo, BuyerPayments
from crispy_forms.layout import Field, Layout, Div, ButtonHolder, Submit


class BuyersForm(ModelForm):
    date_of_birth = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))
    date_of_registration = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(Field('first_name'), css_class='col-md-4', ),
                Div(Field('last_name'), css_class='col-md-4', ),
                Div(Field('middle_name'), css_class='col-md-4', ),
                Div(Field('gender'), css_class='col-md-4', ),
                Div(Field('date_of_birth'), css_class='col-md-4', ),
                Div(Field('residential_status'), css_class='col-md-4', ),
                Div(Field('current_address'), css_class='col-md-4', ),
                Div(Field('national_id'), css_class='col-md-4', ),
                css_class='row',
            ),
            Div(
                Div(Field('kra_pin'), css_class='col-md-4', ),
                Div(Field('passport_photo'), css_class='col-md-4', ),
                Div(Field('buyer_personal_number'), css_class='col-md-4', ),
                Div(Field('buyers_email'), css_class='col-md-4', ),
                Div(Field('mobile_phone'), css_class='col-md-4', ),
                Div(Field('date_of_registration'), css_class='col-md-4', ),
                Div(Field('project_assigned'), css_class='col-md-4', ),
                css_class='row',
            ),
            Div(
                Div(Field('plot_booked'), css_class='col-md-4', ),
                Div(Field('contract_type'), css_class='col-md-4', ),
                Div(Field('deposit_amount'), css_class='col-md-4', ),
                Div(Field('balance_amount'), css_class='col-md-4', ),
                Div(Field('registeredBy'), css_class='col-md-4', ),
                css_class='row',
            ),
            ButtonHolder(
                Submit('submit', 'Save', css_class='button white')
            )
        )
        super(BuyersForm, self).__init__(*args, **kwargs)

    class Meta:
        model = BuyerInfo
        fields = "__all__"


class PaymentForm(ModelForm):
    dateReceived = forms.DateField(widget=forms.TextInput(attrs={'class': 'datepicker'}))

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Div(Field('dateReceived'), css_class='col-md-4', ),
                Div(Field('transactionId'), css_class='col-md-4', ),
                Div(Field('amount'), css_class='col-md-4', ),
                Div(Field('paymentFrom'), css_class='col-md-4', ),
                Div(Field('paymentMethod'), css_class='col-md-4', ),
                Div(Field('paidFor'), css_class='col-md-4', ),
                Div(Field('receivedby'), css_class='col-md-4', ),
                Div(Field('paymentstatus'), css_class='col-md-4', ),
                css_class='row',
            ),
            ButtonHolder(
                Submit('submit', 'Save', css_class='button white')
            )
        )
        super(PaymentForm, self).__init__(*args, **kwargs)



    class Meta:
        model = BuyerPayments
        fields = "__all__"

buyers/views.py
#from pyexpat.errors import messages

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from buyers.forms import BuyersForm, PaymentForm
from buyers.models import BuyerInfo, BuyerPayments
from plots.models import Plot, Plot_Number


@login_required(login_url='/accounts/login/')
def index(request):
    projects = Plot.objects.all()
    project_count = projects.count()

    plots = Plot_Number.objects.all()
    plot_count = plots.count()

    buyers = BuyerInfo.objects.all()
    buyers_count = buyers.count()

    payments = BuyerPayments.objects.all()
    payment_count = payments.count()

    return render(request, 'buyers/index.html',{'buyers_count': buyers_count, 'payment_count': payment_count, 'project_count': project_count, 'plot_count': plot_count})


@login_required(login_url='/accounts/login/')
def buyers(request):
    buyers = BuyerInfo.objects.all()
    if request.method == 'POST':
        form = BuyersForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Buyer added booking successfuly initiated")
        else:
            messages.error(request, "Error adding buyer")
    else:
        form = BuyersForm()
    return render(request, 'buyers/buyers.html', {'buyers':buyers,'buyers_form': form})


@login_required(login_url='/accounts/login/')
def create_buyer(request):
    if request.method == 'POST':
        form = BuyersForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Buyer added booking successfuly initiated")
            return redirect('buyers:buyers')
        else:
            messages.error(request, "Error adding buyer")

    else:
        form = BuyersForm()

    return render(request, 'buyers/buyer.html', {'buyers_form': form})


@login_required(login_url='/accounts/login/')
def buyer_detail(request, buyer_id):
    buyer = get_object_or_404(BuyerInfo, pk=buyer_id)
    return render(request, 'buyers/buyer_detail.html', {'buyer': buyer})


@login_required(login_url='/accounts/login/')
def create_payment(request):
    if request.method == 'POST':
        form = PaymentForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Payment recorded successfully")
            return HttpResponseRedirect('/payments')
        else:
            messages.error(request, "Error recording payment")
    else:
        form = PaymentForm()

    return render(request, 'buyers/payment.html', {'form': form})


@login_required(login_url='/accounts/login/')
def edit_payment(request, payment_id):
    payment = get_object_or_404(BuyerPayments, id=payment_id)
    if request.method == 'POST':
        form = PaymentForm(request.POST, instance=payment)

        if form.is_valid():
            form.save()
            messages.success(request, "Payment updated successfully")
            return HttpResponseRedirect('/payments')
        else:
            messages.error(request, "Error updating payment")
    else:
        form = PaymentForm(instance=payment)

    return render(request, 'buyers/edit_payment.html', {'form': form})


@login_required(login_url='/accounts/login/')
def delete_payment(request, payment_id):
    payment = get_object_or_404(BuyerPayments, id=payment_id)
    payment.delete()
    messages.success(request, "Payment deleted successfully")
    return HttpResponseRedirect('/payments')


@login_required(login_url='/accounts/login/')
def all_payments(request):
    payments = BuyerPayments.objects.all()

    return render(request, 'buyers/payments.html', {'payments': payments})


@login_required(login_url='/accounts/login/')
def buyer_edit(request, buyer_id):
    buyer = BuyerInfo.objects.get(id=buyer_id)

    if request.method == 'POST':
        form = BuyersForm(request.POST, instance=buyer, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "buyer updated successfully")
            return redirect("/buyers")
        else:
            messages.error(request, "error updating the buyer")
    else:
        form = BuyersForm(instance=buyer)
    return render(request, 'buyer_update_form.html', {'buyer': buyer})


@login_required(login_url='/accounts/login/')
def buyer_update(request, buyer_id):
    buyer = BuyerInfo.objects.get(id=buyer_id)

    if request.method == 'POST':
        form = BuyersForm(request.POST, instance=buyer, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "buyer updated successfully")
            return redirect("/buyers")
        else:
            messages.error(request, "error updating the buyer")
    else:
        form = BuyersForm(instance=buyer)
    return render(request, 'buyers/buyer_update_form.html', {'buyer': buyer, 'buyer_form': form})      

templates/buyers/buyer.html
{% extends 'base2.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %} Create buyer {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
    <strong>{{ message|escape }}</strong>
</div>
{% else %}
<div class="alert alert-success">
    <strong>{{ message|escape }}</strong>
</div>
{% endif %}
{% endfor %}
{% endif %}
<div class="container container-fluid">
    <div class="text-center">
        <form method="POST" enctype="multipart/form-data" class="post-form">
            {% csrf_token %}
            {% crispy buyers_form %}
        </form>
    </div>
</div>
{% endblock %}

templates/buyers/buyers.html
{% extends 'base2.html' %}
{% load static %}
{% block title %} Buyers {% endblock %}


{% block content %}
{% load crispy_forms_tags %}
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
    <strong>{{ message|escape }}</strong>
</div>
{% else %}
<div class="alert alert-success">
    <strong>{{ message|escape }}</strong>
</div>
{% endif %}
{% endfor %}
{% endif %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800" style="margin-left:30px">Buyers</h1>
    </div>

    <!-- Content Row -->
    <div class="row" style="margin-left:30px">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading" style="margin-bottom:5px">
                <a href="{% url 'buyers:new_buyer' %}" style="color:white; margin-bottom:20px" class="btn btn-success btn-xs"><i class="fa fa-plus"></i> Add </a>
            </header>
            <!--Modal: modalConfirmDelete-->
            <div class="modal fade" id="add_buyer" tabindex="-1" role="dialog"
                 aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-sm modal-notify modal-danger" role="document">
                    <!--Content-->
                    <form class="form-horizontal tabular-form" enctype="multipart/form-data" method="post">
                        {% csrf_token %}
                        {{buyer_form|crispy }}
                        <div class="panel-footer">
                            <div class="row">
                                <div class="col-sm-8 col-sm-10">
                                    <input type="submit" class="btn-primary btn" value="Save">
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="modal-content text-center">
                        <!--Header-->
                        <div class="modal-header d-flex justify-content-center">
                            <p class="heading">Are you sure?</p>
                        </div>


                        <!--Footer-->
                        <div class="modal-footer flex-center" style="text-align:center">
                            <a href="#" class="btn  btn-success">Yes</a>
                            <a type="button" class="btn  btn-danger waves-effect"
                               data-dismiss="modal">No</a>
                        </div>
                    </div>
                    <!--/.Content-->
                </div>
            </div>
            <!--Modal: modalConfirmDelete-->
            <table class="table table-hover p-table responsive" width="100%" id="buyers">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>National Id</th>
                    <th>Project Assigned</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for buyer in buyers %}
                <tr>
                    <td class="p-name">
                        <a href="{{ buyer.id }}">{{buyer.first_name}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ buyer.id }}">{{buyer.last_name}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ buyer.id }}">{{buyer.national_id}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ buyer.id }}">{{buyer.project_assigned}}</a>
                    </td>
                    <td>
                        <a href="{{ buyer.id }}" class="btn btn-primary btn-xs"><i
                                class="fa fa-folder"></i> View
                        </a>
                        <a href="{{ buyer.id }}/edit" class="btn btn-info btn-xs"><i
                                class="fa fa-pencil"></i> Edit </a>
                        <a role="button" href="{{ buyer.id }}/delete/" style="color:white" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>

{#                        <!--Modal: modalConfirmDelete-->#}
{#                        <div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog"#}
{#                             aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#                            <div class="modal-dialog modal-sm modal-notify modal-danger" role="document">#}
{#                                <!--Content-->#}
{#                                <div class="modal-content text-center">#}
{#                                    <!--Header-->#}
{#                                    <div class="modal-header d-flex justify-content-center">#}
{#                                        <p class="heading">Are you sure?</p>#}
{#                                    </div>#}
{##}
{##}
{#                                    <!--Footer-->#}
{#                                    <div class="modal-footer flex-center" style="text-align:center">#}
{#                                        <a href="{{ buyer.id }}/delete" class="btn  btn-success">Yes</a>#}
{#                                        <a type="button" class="btn  btn-danger waves-effect"#}
{#                                           data-dismiss="modal">No</a>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <!--/.Content-->#}
{#                            </div>#}
{#                        </div>#}
                        <!--Modal: modalConfirmDelete-->
                    </td>
                    {% empty %}
                    <td class="p-name">
                        <a>You haven't added any buyers yet</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>
        <!-- page end-->

    </div>
    <!-- Content Row -->


    <!-- Content Row -->
</div>
<!-- End of Main Content -->

{% endblock %}

templates/buyers/index.html
{% extends 'base2.html' %}
{% load bootstrap4 %}
{% load static %}
{% block title %} Home {% endblock %}


{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
{#        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i#}
{#                class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Projects Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <a href="{% url 'plots:plots' %}">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Projects
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{project_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user-friends fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Plots Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <a href="{% url 'plots:plotnumbers' %}">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Plots
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{plot_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user-friends fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-4 col-md-6 mb-4">
            <a href="{% url 'buyers:buyers' %}">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Buyers
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{buyers_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user-friends fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {#        Payment card#}
        <div class="col-xl-4 col-md-6 mb-4">
            <a href="{% url 'buyers:payments' %}">
                <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                    Payments
                                </div>
                                <div class="h5 mb-0 font-weight-bold text-gray-800">{{payment_count}}</div>
                            </div>
                            <div class="col-auto">
                                <i class="fas fa-user-plus fa-2x text-gray-300"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>

    </div>
    <!-- Content Row -->


    <!-- Content Row -->
</div>
<!-- End of Main Content -->

{% endblock %}

templates/buyers/payments.html
{% extends 'base2.html' %}
{% load static %}
{% block title %} Payments {% endblock %}


{% block content %}
{% load crispy_forms_tags %}
{% if messages %}
{% for message in messages %}
{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger">
    <strong>{{ message|escape }}</strong>
</div>
{% else %}
<div class="alert alert-success">
    <strong>{{ message|escape }}</strong>
</div>
{% endif %}
{% endfor %}
{% endif %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800" style="margin-left:30px">Payments</h1>
    </div>

    <!-- Content Row -->
    <div class="row" style="margin-left:30px">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading" style="margin-bottom:5px">
                <a href="{% url 'buyers:create_payment' %}" style="color:white; margin-bottom:20px" class="btn btn-success btn-xs"><i class="fa fa-plus"></i> Add </a>
            </header>
            <!--Modal: modalConfirmDelete-->
{#            <div class="modal fade" id="add_buyer" tabindex="-1" role="dialog"#}
{#                 aria-labelledby="exampleModalLabel" aria-hidden="true">#}
{#                <div class="modal-dialog modal-sm modal-notify modal-danger" role="document">#}
{#                    <!--Content-->#}
{#                    <form class="form-horizontal tabular-form" enctype="multipart/form-data" method="post">#}
{#                        {% csrf_token %}#}
{#                        {{buyer_form|crispy }}#}
{#                        <div class="panel-footer">#}
{#                            <div class="row">#}
{#                                <div class="col-sm-8 col-sm-10">#}
{#                                    <input type="submit" class="btn-primary btn" value="Save">#}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </form>#}
{##}
{#                    <div class="modal-content text-center">#}
{#                        <!--Header-->#}
{#                        <div class="modal-header d-flex justify-content-center">#}
{#                            <p class="heading">Are you sure?</p>#}
{#                        </div>#}
{##}
{##}
{#                        <!--Footer-->#}
{#                        <div class="modal-footer flex-center" style="text-align:center">#}
{#                            <a href="#" class="btn  btn-success">Yes</a>#}
{#                            <a type="button" class="btn  btn-danger waves-effect"#}
{#                               data-dismiss="modal">No</a>#}
{#                        </div>#}
{#                    </div>#}
{#                    <!--/.Content-->#}
{#                </div>#}
{#            </div>#}
            <!--Modal: modalConfirmDelete-->
            <table class="table table-hover p-table   responsive" width="100%" id="payments">
                <thead>
                <tr>
                    <th>Paid By</th>
                    <th>Paid For</th>
                    <th>Date</th>
                    <th>Payment Method</th>
                    <th>Amount</th>
                    <th>Status</th>
                </tr>
                </thead>
                <tbody>
                {% for payment in payments %}
                <tr>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.paymentFrom}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.paidFor}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.dateReceived}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.paymentMethod}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.amount}}</a>
                    </td>
                    <td class="p-name">
                        <a href="{{ payment.id }}">{{payment.paymentstatus}}</a>
                    </td>

                    <td>
                        <a href="{% url 'buyers:edit_payment' payment.id %}" class="btn btn-info btn-xs"><i
                                class="fa fa-pencil"></i> Edit </a>
                        <a role="button" style="color:white" class="btn btn-danger btn-xs" data-toggle="modal"
                           data-target="#modalConfirm"><i class="fa fa-trash-o"></i> Delete </a>

                        <!--Modal: modalConfirmDelete-->
                        <div class="modal fade" id="modalConfirm" tabindex="-1" role="dialog"
                             aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-sm modal-notify modal-danger" role="document">
                                <!--Content-->
                                <div class="modal-content text-center">
                                    <!--Header-->
                                    <div class="modal-header d-flex justify-content-center">
                                        <p class="heading">Are you sure?</p>
                                    </div>


                                    <!--Footer-->
                                    <div class="modal-footer flex-center" style="text-align:center">
                                        <a href="#" class="btn  btn-success">Yes</a>
                                        <a type="button" class="btn  btn-danger waves-effect"
                                           data-dismiss="modal">No</a>
                                    </div>
                                </div>
                                <!--/.Content-->
                            </div>
                        </div>
                        <!--Modal: modalConfirmDelete-->
                    </td>
                    {% empty %}
                    <td class="p-name">
                        <a>You haven't added any payments yet</a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>
        <!-- page end-->

    </div>
    <!-- Content Row -->


    <!-- Content Row -->
</div>
<!-- End of Main Content -->

{% endblock %}