burotimaguta/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from buyers import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('buyers.urls')),
    path('', include('plots.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buyers/urls.py
from django.contrib import admin
from django.urls import path
from buyers import views

app_name="buyers"
urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('buyers/', views.buyers, name='buyers'),
    path('buyers/new/', views.create_buyer, name='new_buyer'),
    path('buyers/<int:buyer_id>/', views.buyer_detail, name='buyer_detail'),
    path('buyers/<int:buyer_id>/edit/', views.buyer_update, name='buyer_update'),
    path('payments/', views.all_payments, name='payments'),
    path('payments/new/', views.create_payment, name='create_payment'),
    path('payments/<int:payment_id>/edit/', views.edit_payment, name='edit_payment'),
    path('payments/<int:payment_id>/delete/', views.delete_payment, name='delete_payment')
]

plots/urls.py
from django.urls import path
from plots import views

app_name="plots"
urlpatterns = [
    path('plots/', views.plots, name='plots'),
    path('plots/<int:plot_id>/', views.plot_detail, name='plot_detail'),
    path('plotnumbers/', views.all_plotnumbers, name='plotnumbers'),
    #path('plotnumbers/<int:plotnumber_id>/', views.plotnumber_detail, name='plotnumber_detail')   
]

templates/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% if title %}
        <title></title>
        {% else %}
        <title>Warda | Payroll</title>
        {% endif %}

        {% block styles %}
        {% bootstrap_css %}

        {% endblock %}
        <link rel="shortcut icon" type="image/png" href="{% static 'images/logo.jpg' %}">
        <link href="https://fonts.googleapis.com/css?family=Antic+Slab|Della+Respira|Frank+Ruhl+Libre|Julius+Sans+One|Nixie+One|Saira" rel="stylesheet">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">
    </head>

    <body>
        {% include 'navbar.html' %}

        {% block content %}

        {% endblock %}

        {% block scripts %}
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
            <script src= "{% static 'js/ajax.js'%}"></script>

        {% bootstrap_javascript %}
        {% endblock %}

    </body>

</html>

templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %} {% endblock %}</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'theme/vendor/fontawesome-free/css/all.min.css'  %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'theme/css/sb-admin-2.min.css'  %}" rel="stylesheet">
    <link href="{% static 'css/app.css'  %}" rel="stylesheet">

    <link href="{% static 'jquerui/jquery-ui.css' %}" rel='stylesheet' type='text/css'/>

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js"
            integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>
    <link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" rel='stylesheet' type='text/css'/>

</head>

<body id="page-top">
<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'buyers:index' %}">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-money-check-alt"></i>
            </div>
            <div class="sidebar-brand-text mx-3">LandSale Management System</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'buyers:index' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'plots:plots' %}">
                <i class="fas fa-fw fa-user-friends"></i>
                <span>Projects</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'plots:plotnumbers' %}">
                <i class="fas fa-fw fa-plus"></i>
                <span>Plots</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'buyers:buyers' %}">
                <i class="fas fa-fw fa-user-friends"></i>
                <span>Buyers</span></a>
        </li>

        <li class="nav-item active">
            <a class="nav-link" href="{% url 'buyers:payments' %}">
                <i class="fas fa-fw fa-plus"></i>
                <span>Payments</span></a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">
        <!-- Divider -->

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Nav Item - Alerts -->

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.username}}</span>
                            <i class="far fa-user-circle"></i>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" href="{% url 'password_change' %}">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Change Password
                            </a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->
            {% block content %}

            {% endblock %}

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright Bray| Humpback Field Solutions 2022</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'theme/vendor/jquery/jquery.min.js'  %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="{% static 'jquerui/jquery-ui.js'  %}"></script>
    <script src="{% static 'theme/vendor/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>


    <!-- Core plugin JavaScript-->
    <script src="{% static 'theme/vendor/jquery-easing/jquery.easing.min.js'  %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'theme/js/sb-admin-2.min.js'  %}"></script>


    <script>
      $(function() {
        $( ".datepicker" ).datepicker({
          changeMonth: true,
          changeYear: true,
          maxDate: 0
          // You can put more options here.

        });
      });

    </script>
    <script>
     $(document).ready(function() {
        $('#buyers').DataTable();
    });

    </script>
    <script>
     $(document).ready(function() {
        $('#payments').DataTable();
    });
    </script>
</div>

</body>

</html>

templates/base3.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>{% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'theme/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'theme/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-3 d-none d-lg-block"></div>
              <div class="col-lg-6">
               {% block body %}

               {% endblock %}
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'theme/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'theme/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'theme/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'theme/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

templates/navbar.html
{#{% load static%}#}
{##}
{##}
{#<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-fixed-top">#}
{#  <a class="navbar-brand" href="/">#}
{#    <img src="{% static 'images/logo.jpg'%}" width="190" height="35" class="d-inline-block align-top" alt="">#}
{#  </a>#}
{#  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">#}
{#    <span class="navbar-toggler-icon"></span>#}
{#  </button>#}
{#  <div class="collapse navbar-collapse" id="navbarNavDropdown">#}
{#    <div class="col-md-4"></div>#}
{#    <div class="col-md-6">#}
{#    <ul class="navbar-nav">#}
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'new_buyer' %}">Create buyer</a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% url 'all_buyers' %}">All-Employees</a>#}
{#      </li>#}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="">Reports</a>#}
{#      </li>#}
{##}
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="#">Releases</a>#}
{#      </li>#}
{#      <!-- <li class="nav-item dropdown">#}
{#        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#          Dropdown link#}
{#        </a>#}
{#        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">#}
{#          <a class="dropdown-item" href="#">Action</a>#}
{#          <a class="dropdown-item" href="#">Another action</a>#}
{#          <a class="dropdown-item" href="#">Something else here</a>#}
{#        </div>#}
{#      </li> -->#}
{#    </ul>#}
{##}
{#</div>#}
{#    <div class="col-md-2">#}
{#      <ul class="navbar-nav navbar-right">#}
{##}
{#        {%if user.is_authenticated %}#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="">{{request.user.username}}</a>#}
{#        </li>#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="">Sign Out</a>#}
{#        </li>#}
{#        {% else %}#}
{#        <li class="nav-item">#}
{#          <a class="nav-link" href="">Sign In</a>#}
{#        </li>#}
{#        {% endif %}#}
{#      </ul>#}
{#    </div>#}
{##}
{#  </div>#}
{#</nav>#}
{##}